# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-17 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppSoftResources', '0002_auto_20190717_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
            ],
            options={
                'verbose_name': '\u5e94\u7528\u90e8\u7f72',
                'proxy': True,
                'verbose_name_plural': '\u5e94\u7528\u90e8\u7f72',
            },
            bases=('AppSoftResources.data',),
        ),
        migrations.CreateModel(
            name='Middleware',
            fields=[
            ],
            options={
                'verbose_name': '\u4e2d\u95f4\u4ef6',
                'proxy': True,
                'verbose_name_plural': '\u4e2d\u95f4\u4ef6',
            },
            bases=('AppSoftResources.data',),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
            ],
            options={
                'verbose_name': '\u5e94\u7528\u7cfb\u7edf',
                'proxy': True,
                'verbose_name_plural': '\u5e94\u7528\u7cfb\u7edf',
            },
            bases=('AppSoftResources.data',),
        ),
    ]
