# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5de5\u4f5c\u7ec4')),
            ],
            options={
                'verbose_name_plural': '\u6dfb\u52a0\u5de5\u4f5c\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Addsystemname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7cfb\u7edf\u540d\u79f0')),
            ],
            options={
                'verbose_name_plural': '\u6dfb\u52a0\u7cfb\u7edf\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='czyylx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u627f\u8f7d\u5e94\u7528\u7c7b\u578b')),
            ],
            options={
                'verbose_name_plural': '\u6dfb\u52a0\u5e94\u7528\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I6000', models.CharField(choices=[('yes', '\u662f'), ('no', '\u5426')], max_length=10)),
                ('xtjslx', models.CharField(choices=[('tt', '\u7edf\u63a8 '), ('zj', '\u81ea\u5efa')], max_length=10, verbose_name='\u7cfb\u7edf\u5efa\u8bbe\u7c7b\u578b')),
                ('bslx', models.CharField(max_length=20, verbose_name='\u90e8\u7f72\u7c7b\u578b')),
                ('yunxingzhuangtai', models.CharField(choices=[('jsz', '\u5efa\u8bbe\u4e2d '), ('zy', '\u5728\u8fd0')], max_length=10, verbose_name='\u4e1a\u52a1\u8d23\u4efb\u90e8\u95e8')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5e94\u7528\u8bbf\u95eeURL')),
                ('xtsxsj', models.DateField(blank=True, null=True, verbose_name='\u7cfb\u7edf\u4e0a\u7ebf\u65f6\u95f4')),
                ('xtxxsj', models.DateField(blank=True, null=True, verbose_name='\u7cfb\u7edf\u4e0b\u7ebf\u65f6\u95f4')),
                ('ip', models.CharField(max_length=100, verbose_name='IP\u5730\u5740')),
                ('xunijiqunip', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u96c6\u7fa4IP')),
                ('xitongsuoshuwangluo', models.CharField(choices=[('jsz', '\u5185\u7f51'), ('zy', '\u5916\u7f51')], max_length=10, verbose_name='\u7cfb\u7edf\u6240\u5c5e\u7f51\u7edc')),
                ('zjczzb', models.CharField(max_length=100, verbose_name='\u4e3b\u673a\u627f\u8f7d\u6307\u6807\u9879')),
                ('zhkx', models.CharField(choices=[('wlj', '\u7269\u7406\u673a'), ('xnj', '\u865a\u62df\u673a')], max_length=10, verbose_name='\u4e3b\u673a\u7c7b\u578b')),
                ('jfxx', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u623f\u4fe1\u606f')),
                ('fwqms', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1\u5668\u63cf\u8ff0')),
                ('yjpp', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u4ef6\u54c1\u724c')),
                ('yjxh', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u4ef6\u578b\u53f7')),
                ('tyrq', models.DateField(blank=True, null=True, verbose_name='\u6295\u8fd0\u65e5\u671f')),
                ('usedate', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f7f\u7528\u5e74\u9650')),
                ('czxtlx', models.CharField(max_length=10, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('czxtbb', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
                ('chzyymc', models.CharField(max_length=100, verbose_name='\u627f\u8f7d\u5e94\u7528\u540d\u79f0')),
                ('czyybb', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u627f\u8f7d\u5e94\u7528\u7248\u672c')),
                ('czyycxazml', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u627f\u8f7d\u5e94\u7528\u7a0b\u5e8f\u5b89\u88c5\u76ee\u5f55')),
                ('fwdkqd', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u7aef\u53e3\u6e05\u5355')),
                ('ywzzr', models.CharField(max_length=100, verbose_name='\u8fd0\u7ef4\u8d23\u4efb\u4eba')),
                ('lxdh', models.CharField(max_length=100, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('ywmail', models.CharField(max_length=100, verbose_name='\u90ae\u7bb1')),
                ('zhuanzephone', models.CharField(max_length=100, verbose_name='\u4e13\u8d23\u7535\u8bdd')),
                ('zzmail', models.CharField(max_length=100, verbose_name='\u4e13\u8d23\u90ae\u7bb1')),
                ('zongbulianxiren', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u603b\u90e8\u8054\u7cfb\u4eba')),
                ('zongbulianxi', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u603b\u90e8\u8054\u7cfb\u65b9\u5f0f')),
                ('youxiang', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u603b\u90e8\u90ae\u7bb1')),
                ('yanfadan', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7814\u53d1\u5355\u4f4d\u540d\u79f0')),
                ('beizhu', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('date', models.DateTimeField(auto_now=True)),
                ('czyylx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoftResources.czyylx', verbose_name='\u627f\u8f7d\u5e94\u7528\u7c7b\u578b')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoftResources.Addgroup', verbose_name='\u5de5\u4f5c\u7ec4')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoftResources.Addsystemname', verbose_name='\u7cfb\u7edf\u540d\u79f0')),
            ],
            options={
                'verbose_name_plural': '\u8d44\u4ea7\u4fe1\u606f\u5f55\u5165',
            },
        ),
        migrations.CreateModel(
            name='Yewuzerenbumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4e1a\u52a1\u8d23\u4efb\u90e8\u95e8')),
            ],
            options={
                'verbose_name_plural': '\u6dfb\u52a0\u4e1a\u52a1\u8d23\u4efb\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='Zhuanze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4e13\u8d23')),
            ],
            options={
                'verbose_name_plural': '\u6dfb\u52a0\u4e13\u8d23',
            },
        ),
        migrations.CreateModel(
            name='Zhuanzhebushi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u8fd0\u7ef4\u8d23\u4efb\u90e8\u5ba4')),
            ],
            options={
                'verbose_name_plural': '\u6dfb\u52a0\u8fd0\u7ef4\u8d23\u4efb\u90e8\u5ba4',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='ywbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoftResources.Zhuanzhebushi', verbose_name='\u8fd0\u7ef4\u8d23\u4efb\u90e8\u5ba4'),
        ),
        migrations.AddField(
            model_name='data',
            name='ywzrbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoftResources.Yewuzerenbumen', verbose_name='\u4e1a\u52a1\u8d23\u4efb\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='data',
            name='zhuanze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoftResources.Zhuanze', verbose_name='\u4e13\u8d23'),
        ),
    ]
