# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-17 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoftResources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='group',
            new_name='groupname',
        ),
    ]
