# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-22 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoftResources', '0003_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addgroup',
            options={},
        ),
    ]
