# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-22 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoftResources', '0004_auto_20190722_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addgroup',
            options={'verbose_name_plural': '\u6dfb\u52a0\u5de5\u4f5c\u7ec4'},
        ),
    ]
